name: Build and Push MSYS2 Base Images

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push (Linux)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.linux
          push: true
          tags: |
            africanfuture/msys2-base:linux
            africanfuture/msys2-base:linux-latest
          platforms: linux/amd64

# Uncomment the below job when ready to build Windows container (requires Windows-compatible environment)
#  build-windows:
#    runs-on: windows-latest
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v4
#
#      - name: Login to Docker Hub
#        uses: docker/login-action@v3
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
#
#      - name: Build image (Windows)
#        run: |
#          $env:DOCKER_BUILDKIT = "0"
#          $buildOutput = docker build --isolation=process -f Dockerfile.windows -t africanfuture/msys2-base:windows . 2>&1
#          $buildOutput | Out-File -FilePath build.log
#          if ($LASTEXITCODE -ne 0) { throw "Build failed with exit code $LASTEXITCODE" }
#        shell: powershell
#
#      - name: Push image (Windows)
#        run: |
#          docker tag africanfuture/msys2-base:windows africanfuture/msys2-base:windows-latest
#          docker push africanfuture/msys2-base:windows
#          docker push africanfuture/msys2-base:windows-latest
#        shell: powershell
#
#      - name: Capture build output on failure (Windows)
#        if: failure()
#        run: |
#          Get-Content build.log
#        shell: powershell
